function postit(){
var ref = new Firebase("https://boiling-heat-5681.firebaseio.com/");
var postsRef = ref.child("Medicines");
var newPostRef = postsRef.push({
  MedName: $('#MedName').val(),
  Timestamp: Firebase.ServerValue.TIMESTAMP
});
// Get the unique ID generated by push()
var postID = newPostRef.name();
var uidset = postsRef.child(postID);
console.log(uidset);
uidset.update({
  MedName: $('#MedName').val(),
  Timestamp: Firebase.ServerValue.TIMESTAMP,
  UID: postID
});
$('#MedName').val('');
}

function removeit(){
var ref = new Firebase("https://boiling-heat-5681.firebaseio.com/");
var postsRef = ref.child("Medicines");
var uid = postsRef.child(grabid);
uid.remove();
rerun();
$('#result').select2();

}
